import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";
import Header from "../components/Header";
import Content from "./Content";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Notetaker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        {sessionData?.user.id ? (
          <Content />
        ) : (
          <div className="flex h-screen">
            <div className="m-auto">Please login to jot it down</div>
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
